### ISSUE TITLE
Docs - Migration Guide for WTS projects

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/MVVM-Samples#17]
As requested here: https://twitter.com/carlomendoza/status/1293584362219302912?s=20

We should have a guide for helping folks with WTS migration when that issue is resolved here: https://github.com/microsoft/WindowsTemplateStudio/issues/3753

**Comment by myokeeh** [comment]
Reference: https://twitter.com/carlomendoza/status/1296202798959271936?s=20

I think the preliminary documentation in https://github.com/windows-toolkit/MVVM-Samples/pull/14 helps port a test app I made with WTS (Navigation View) but I'm a bit unsure about the `SimpleIoc` to `Ioc` parts.

Code below allows the app to build, but won't launch with an `UnhandledException` 

> Cannot add instance of type 'DELETE3.Behaviors.NavigationViewHeaderBehavior' to a collection of type 'Microsoft.Xaml.Interactivity.BehaviorCollection'. [Line: 48 Position: 80]

This is autogenerated by WTS in ViewModelLocator.cs:
```
private ViewModelLocator()
{
    SimpleIoc.Default.Register(() => new NavigationServiceEx());
    SimpleIoc.Default.Register<ShellViewModel>();
    Register<MainViewModel, MainPage>();
    Register<SettingsViewModel, SettingsPage>();
}
```

Per the preliminary documentation, is this correct?

```
private ViewModelLocator()
{
    Ioc.Default.ConfigureServices(services =>
            {
                services.AddSingleton<NavigationServiceEx>();
                services.AddSingleton<ShellViewModel>();
            });
    Register<MainViewModel, MainPage>();
    Register<SettingsViewModel, SettingsPage>();
}
```

And further down:
By WTS:
```
public void Register<VM, V>() where VM : class
{
            SimpleIoc.Default.Register<VM>();
            NavigationService.Configure(typeof(VM).FullName, typeof(V));
}
```
Per the preliminary documentation, is this correct?
```
public void Register<VM, V>() where VM : class
{
            Ioc.Default.ConfigureServices(services =>
            {
                services.AddSingleton<VM>();
            });
            NavigationService.Configure(typeof(VM).FullName, typeof(V));
}
```

**Comment by Sergio0694** [comment]
Hey @myokeeh - you're getting that crash because you're calling `ConfigureServices` more than once. You can only use that method once on a given `Ioc` instance (`Ioc.Default` in this case), as `IServiceProvider` instances are immutable (that's the same behavior from the `Microsoft.Extensions.DependencyInjection`).

You'll need to register all your services together in a single call to avoid that startup crash.

**Comment by myokeeh** [comment]
@Sergio0694 That's a bit of clarification for me. However, I think there's a disconnect in my understanding of using it for the `ViewModel`s and `Page`s vs `TService`s and  `TImplementation`s for `AddSingleton`

From you've told me, it appears I shouldn't even have the  `public void Register<VM, V>() where VM : class {...}` and have all the ViewModels registered and configured in `Ioc.Default.ConfigureServices(services => {...});`

This is likely going to be a lot clearer (or something I don't have to worry about) when fully implemented in the WTS templates, but I'm a little excited (or careful) to test everything in advance.

**Comment by myokeeh** [comment]
It appears I've got it back into a working state with MVVM Toolkit now. Thanks for the guidance.

```
private ViewModelLocator()
{
    Ioc.Default.ConfigureServices(services =>
    {
        services.AddSingleton<NavigationServiceEx>();
        services.AddSingleton<ShellViewModel>();
        services.AddSingleton<MainViewModel>();
        services.AddSingleton<SettingsViewModel>();
    });
    NavigationService.Configure(typeof(MainViewModel).FullName, typeof(MainPage));
    NavigationService.Configure(typeof(SettingsViewModel).FullName, typeof(SettingsPage));
}
```

and removed `public void Register<VM, V>() where VM : class {...}`

**Comment by Sergio0694** [comment]
Hey @myokeeh - sorry for the delay!
That is correct, you're supposed to inject all your services in a single place, so that once you initialize the `IServiceProvider` instance for your application, that'll always remain the same while the app runs. It basically is "closed" right after initialization. Your solution is exactly the right way to use this - just have a single `ConfigureServices` call and do your setup there.

**Bonus point:** if you're interested, and also to help with code modularity, you might want to consider ditching the service locator pattern and switch to full dependency injection. That'd let you only care about that setup part in your view, and then all your viewmodels would just have all the necessary services injected directly into them, which makes the code easier to refactor and without strong references to that viewmodel locator class. Also, is this class used in your viewmodel? Because I see you have a strong reference to two XAML types (those two pages). Ideally you'd want to completely separate your backend into a .NET Standard project to make sure all your backend is completely self contained and platform agnostic.

Just a side note, you don't actually need to change your code if it works fine for you for now! 😊

**Comment by myokeeh** [comment]
@Sergio0694 thanks for the additional guidance. I tend to keep my apps close to Windows Template Studio "stock" so it's easy for me to compare and maintain. I'd ditch the service locator pattern if that's what WTS does. I haven't quite made the push to separate things into a .NET Standard project since my apps have been Desktop only ever since Windows 10 Mobile was killed 😞.

I get nervous when things stop getting supported and like to try upcoming stuff. All my apps started with Template10, then ported to WTS (Mvvm Light). It looks like I'll port them to WTS with MVVM Toolkit, soon.
