### ISSUE TITLE
Build Fails after updating to 7.0.0-preview3 via Nuget

### ISSUE THREAD

**Issue by mdockal** [windows-toolkit/MVVM-Samples#27]
Updated MVVM-Samples NuGet packages to 7.0.0-preview3.   Build failed due to missing Ioc class and references.  Since @Sergio0694 committed [Removed Ioc class and MS.Ex.DI dependency](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3429/commits/0bd1f92ad00dff22afbc832d197322e22055668c).   How do I fix this?   Do I use SimpleIoc?  Also, the IocPage needs to be upated.

**Comment by Sergio0694** [comment]
That is correct, the `Ioc` class was removed in Preview 3 (though we plan to reintroduce it with some differences in the future). I have update the docs page ([here](https://github.com/windows-toolkit/MVVM-Samples/blob/master/docs/mvvm/Ioc.md)) to include a guide that shows how to properly setup a DI architecture in your application. If you do want to use the `Ioc` class from your viewmodels instead (ie. using the service locator pattern instead of DI), you'll need to wait for the next update of the MVVM Toolkit to ship, or just temporarily copy the updated `Ioc` class from the PR ([here](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3527)).

Let me know if this helps! 😄

**Comment by michael-hawker** [comment]
@mdockal we've updated the package to reintroduce an IoC helper (and updated the docs here as Sergio mentioned).

You can see the list of changes in the tracking issue here: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3428

@Sergio0694 can you update the Changelog here too with the prettified version you do so well?
